# Install docker and docker-compose on service hosts
- hosts: all
  become: true
  vars:
    ansible_port: 22
    ansible_user: ubuntu
    private_key_file: "../keys/service_key.pem"
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -i ../keys/bastion_key.pem ubuntu@65.2.144.94"'
  tasks:
    - name: Debug
      ansible.builtin.debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        [
          "apt-transport-https",
          "ca-certificates",
          "curl",
          "software-properties-common",
          "python3-pip",
          "virtualenv",
          "python3-setuptools",
        ]

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt
      apt: update_cache=yes

    - name: Install docker and docker-compose
      apt: name={{ item }} state=latest
      loop: ["docker-ce", "docker-compose"]
